version: "3"
services:
  backend:
    ports:
      - "8080:8080"
    image: "pressx-dev-backend"
    build:
      context: "backend"
      dockerfile: "development.Dockerfile"
    working_dir: "/backend"
    command: sh -c "go get -v && go get github.com/cortesi/modd/cmd/modd && modd"
    volumes:
      - ./backend:/backend
  admin:
    ports:
      - "1234:1234"
      - "46341:46341"
    image: "pressx-dev-admin"
    build:
      context: "admin"
      dockerfile: "development.Dockerfile"
    working_dir: "/admin"
    command: sh -c "npm i && npm start"
    volumes:
      - ./admin:/admin
